### ISSUE TITLE
Please Stop Blocking Me!

### ISSUE THREAD

**Issue by samuraininja360** [GrahamSH-LLK/grahamsh-llk.github.io#1]
Why did you have to block me again? How did my pull request breach any code of conduct. I just got blocked last week andn now I am blocked again.

**Comment by GrahamSH-LLK** [comment]
> Why did you have to block me again? How did my pull request breach any code of conduct. I just got blocked last week andn now I am blocked again.

A. This is a repo for _my personal_ website. 
B. I have no control over you getting blocked.

**Comment by GrahamSH-LLK** [comment]
@samuraininja360 By the way, you've been unbanned.
